# 为 dsh-harness-control 创建桌面快捷方式（唯一入口）
#   「DSH Harness」—— 双击 = 启动后台 GUI（未运行则自动拉起）+ 自动打开浏览器 + 系统托盘就位
#   之后全用托盘菜单管理：停止 / 重启 / 端口设置 / 打开界面
#
# 用法:
#   powershell -ExecutionPolicy Bypass -File install.ps1
#   powershell -ExecutionPolicy Bypass -File install.ps1 -AutoStart        # 开机自启（登录时自动启动托盘）
#   powershell -ExecutionPolicy Bypass -File install.ps1 -RemoveAutoStart  # 取消开机自启
param(
  [string]$RepoRoot = $PSScriptRoot,
  [switch]$AutoStart,
  [switch]$RemoveAutoStart
)

$ErrorActionPreference = 'Stop'

$trayPs1 = Join-Path $RepoRoot 'dsh-tray.ps1'
if (-not (Test-Path $trayPs1)) { throw "dsh-tray.ps1 not found in $RepoRoot" }

$icon  = Join-Path $RepoRoot 'dsh-tray.ico'
$desktop = [Environment]::GetFolderPath('Desktop')
$startup = [Environment]::GetFolderPath('Startup')
$ws = New-Object -ComObject WScript.Shell

# 开机自启：把启动命令放进「启动」文件夹（用户级，无需管理员）
if ($AutoStart) {
  $cmd = Join-Path $startup 'DSH Harness.cmd'
  $content = @"
@echo off
rem DSH Harness tray autostart (generated by install.ps1 -AutoStart)
start "" powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "$trayPs1"
"@
  [System.IO.File]::WriteAllText($cmd, $content, (New-Object System.Text.UTF8Encoding($false)))
  Write-Host "autostart enabled: $cmd"
}
if ($RemoveAutoStart) {
  $cmd = Join-Path $startup 'DSH Harness.cmd'
  if (Test-Path $cmd) { Remove-Item $cmd -Force; Write-Host "autostart removed: $cmd" }
  else { Write-Host "no autostart entry found" }
}
if ($AutoStart -or $RemoveAutoStart) { return }

# 桌面快捷方式（唯一入口）
$lnk = Join-Path $desktop 'DSH Harness.lnk'
$sc = $ws.CreateShortcut($lnk)
$sc.TargetPath       = 'powershell.exe'
$sc.Arguments        = "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$trayPs1`""
$sc.WorkingDirectory = $RepoRoot
$sc.Description      = '一键启动 DeepSeek Harness 后台 GUI（自动打开浏览器），托盘常驻管理：停止/重启/端口设置'
$sc.IconLocation     = if (Test-Path $icon) { "$icon,0" } else { 'shell32.dll,134' }
$sc.Save()
Write-Host "shortcut created: $lnk"
