# 为 dsh-harness-control 创建桌面快捷方式（唯一入口）
#   「DSH Harness」—— 双击 = 启动后台 GUI（未运行则自动拉起）+ 自动打开浏览器 + 系统托盘就位
#   之后全用托盘菜单管理：停止 / 重启 / 端口设置 / 打开界面
#
# 用法:
#   powershell -ExecutionPolicy Bypass -File install.ps1
#   powershell -ExecutionPolicy Bypass -File install.ps1 -AutoStart        # 开机自启（会先询问确认，除非加 -Yes）
#   powershell -ExecutionPolicy Bypass -File install.ps1 -AutoStart -Yes   # 跳过确认，直接启用（脚本化场景）
#   powershell -ExecutionPolicy Bypass -File install.ps1 -RemoveAutoStart  # 取消开机自启
param(
  [string]$RepoRoot = $PSScriptRoot,
  [switch]$AutoStart,
  [switch]$RemoveAutoStart,
  [switch]$Yes
)

$ErrorActionPreference = 'Stop'

$trayPs1 = Join-Path $RepoRoot 'dsh-tray.ps1'
if (-not (Test-Path $trayPs1)) {
  throw "dsh-tray.ps1 not found in $RepoRoot — 请确认在仓库根目录运行本脚本，或用 -RepoRoot 指定正确目录"
}

$icon  = Join-Path $RepoRoot 'dsh-tray.ico'
$desktop = [Environment]::GetFolderPath('Desktop')
$startup = [Environment]::GetFolderPath('Startup')
$ws = New-Object -ComObject WScript.Shell

# 环境提示（不阻塞安装; 运行时托盘/脚本会再次检查并弹窗）
$nodeCmd = Get-Command node -ErrorAction SilentlyContinue
if (-not $nodeCmd) {
  Write-Host "⚠ 未检测到 Node.js（DeepSeek Harness 需要 >= 22）。快捷方式仍会创建，但启动时会有明确报错；建议先装: https://nodejs.org"
}
else {
  try {
    $nv = & $nodeCmd.Source --version 2>$null
    if ($nv -match 'v?(\d+)\.' -and [int]$matches[1] -lt 22) {
      Write-Host "⚠ Node.js 版本过低 (v$($matches[1]).x)，DeepSeek Harness 需要 >= 22，建议升级后再启动"
    }
  } catch { }
}

# 开机自启：把启动命令放进「启动」文件夹（用户级，无需管理员）
# 涉及系统行为变更，必须征得用户明确同意才执行
if ($AutoStart) {
  $cmd = Join-Path $startup 'DSH Harness.cmd'
  if (-not $Yes) {
    $ans = Read-Host @"
即将创建开机自启项：
  $cmd
效果：每次登录后自动启动托盘，托盘会自动拉起后台 GUI 并打开浏览器。
确认启用开机自启？(y/N)
"@
    if ($ans -ne 'y' -and $ans -ne 'Y') {
      Write-Host "已取消，未启用开机自启。"
      return
    }
  }
  $content = @"
@echo off
rem DSH Harness tray autostart (generated by install.ps1 -AutoStart)
start "" powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "$trayPs1"
"@
  [System.IO.File]::WriteAllText($cmd, $content, (New-Object System.Text.UTF8Encoding($false)))
  Write-Host "autostart enabled: $cmd"
}
if ($RemoveAutoStart) {
  $cmd = Join-Path $startup 'DSH Harness.cmd'
  if (Test-Path $cmd) { Remove-Item $cmd -Force; Write-Host "autostart removed: $cmd" }
  else { Write-Host "no autostart entry found" }
}
if ($AutoStart -or $RemoveAutoStart) { return }

# 桌面快捷方式（唯一入口）
$lnk = Join-Path $desktop 'DSH Harness.lnk'
$sc = $ws.CreateShortcut($lnk)
$sc.TargetPath       = 'powershell.exe'
$sc.Arguments        = "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$trayPs1`""
$sc.WorkingDirectory = $RepoRoot
$sc.Description      = '一键启动 DeepSeek Harness 后台 GUI（自动打开浏览器），托盘常驻管理：停止/重启/端口设置'
$sc.IconLocation     = if (Test-Path $icon) { "$icon,0" } else { 'shell32.dll,134' }
$sc.Save()
Write-Host "shortcut created: $lnk"
